### ISSUE TITLE
Halite: Halite amount can grow negative

### ISSUE THREAD

**Issue by janjagusch** [Kaggle/kaggle-environments#13]
Currently, the amount of halite stored in a cell can grow negative.

This is due to an implementation detail in the [interpreter](https://github.com/Kaggle/kaggle-environments/blob/master/kaggle_environments/envs/halite/halite.py#L330).

```python
elif obs.halite[ship_pos] > 0:
    collect_halite = max(
        1, int(obs.halite[ship_pos] * config.collectRate))
    obs.halite[ship_pos] -= collect_halite
```

At least one unit of halite always gets deducted from the cell. When the cell contains less than 1 unit of halite, this value becomes negative. Interestingly, it then starts growing negative halite exponentially, based on the `configuration.RegenRate`.

Thanks to Tom Van de Wiele for identifying the behaviour and adding it to the [discussion](https://www.kaggle.com/c/halite/discussion/144929).

## Proposed solution

I personally believe it would simplify things dramatically if halite was stored in integers rather than float throughout the game. It also aligns better with my understanding of halite as being an atomic resource. In most comparable resource management games (AoE, StarCraft, Strongold, ...) resources are usually tracked in integers as well.

**Comment by harrisse** [comment]
Thanks! I understand the logic of int-based halite everywhere. The reason we chose float based halite is to have smoother reconciliation with exponential changes in halite over time. E.g. if halite grows at 2% per step, that won't cause appropriate changes in cells with less than 50 halite.

For the next round of halite changes we'll only allow you to collect from a cell if you could collect at least 1 halite, otherwise you'll get 0 until the cell accumulates enough halite to collect 1. From a lore perspective, let's say that halite is continuous in the wild, but is stored in 1 unit containers when actually loaded onto your ship.

**Comment by harrisse** [comment]
This should now be resolved, thanks for the report!
